//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPublisher.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://github.com/Claude-He/WcfEnsFx", ConfigurationName="ServiceReference.IMyEvent")]
    public interface IMyEvent {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://github.com/Claude-He/WcfEnsFx/IMyEvent/DemoEvent", ReplyAction="https://github.com/Claude-He/WcfEnsFx/IMyEvent/DemoEventResponse")]
        void DemoEvent(string eventMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://github.com/Claude-He/WcfEnsFx/IMyEvent/DemoEvent", ReplyAction="https://github.com/Claude-He/WcfEnsFx/IMyEvent/DemoEventResponse")]
        System.Threading.Tasks.Task DemoEventAsync(string eventMessage);


        [System.ServiceModel.OperationContractAttribute(Action = "https://github.com/Claude-He/WcfEnsFx/IMyEvent/DemoEvent", ReplyAction = "https://github.com/Claude-He/WcfEnsFx/IMyEvent/DemoEventResponse")]
        void DemoEvent(string eventMessage, int intParam);

        [System.ServiceModel.OperationContractAttribute(Action = "https://github.com/Claude-He/WcfEnsFx/IMyEvent/DemoEvent", ReplyAction = "https://github.com/Claude-He/WcfEnsFx/IMyEvent/DemoEventResponse")]
        System.Threading.Tasks.Task DemoEventAsync(string eventMessage, int intParam);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMyEventChannel : MyPublisher.ServiceReference.IMyEvent, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyEventClient : System.ServiceModel.ClientBase<MyPublisher.ServiceReference.IMyEvent>, MyPublisher.ServiceReference.IMyEvent {
        
        public MyEventClient() {
        }
        
        public MyEventClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyEventClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyEventClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyEventClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DemoEvent(string eventMessage) {
            base.Channel.DemoEvent(eventMessage);
        }
        
        public System.Threading.Tasks.Task DemoEventAsync(string eventMessage) {
            return base.Channel.DemoEventAsync(eventMessage);
        }

        public void DemoEvent(string eventMessage, int intParam)
        {
            base.Channel.DemoEvent(eventMessage, intParam);
        }

        public System.Threading.Tasks.Task DemoEventAsync(string eventMessage, int intParam)
        {
            return base.Channel.DemoEventAsync(eventMessage, intParam);
        }
    }
}
