//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyForms.SubscriptionServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://github.com/Claude-He/WcfEnsFx", ConfigurationName="SubscriptionServiceRef.IMyService", CallbackContract=typeof(MyForms.SubscriptionServiceRef.IMyServiceCallback))]
    public interface IMyService {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://tempuri.org/) of message SubscribeRequest does not match the default value (https://github.com/Claude-He/WcfEnsFx)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnsSubscription/Subscribe", ReplyAction="http://tempuri.org/IEnsSubscription/SubscribeResponse")]
        MyForms.SubscriptionServiceRef.SubscribeResponse Subscribe(MyForms.SubscriptionServiceRef.SubscribeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnsSubscription/Subscribe", ReplyAction="http://tempuri.org/IEnsSubscription/SubscribeResponse")]
        System.Threading.Tasks.Task<MyForms.SubscriptionServiceRef.SubscribeResponse> SubscribeAsync(MyForms.SubscriptionServiceRef.SubscribeRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://tempuri.org/) of message UnsubscribeRequest does not match the default value (https://github.com/Claude-He/WcfEnsFx)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnsSubscription/Unsubscribe", ReplyAction="http://tempuri.org/IEnsSubscription/UnsubscribeResponse")]
        MyForms.SubscriptionServiceRef.UnsubscribeResponse Unsubscribe(MyForms.SubscriptionServiceRef.UnsubscribeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnsSubscription/Unsubscribe", ReplyAction="http://tempuri.org/IEnsSubscription/UnsubscribeResponse")]
        System.Threading.Tasks.Task<MyForms.SubscriptionServiceRef.UnsubscribeResponse> UnsubscribeAsync(MyForms.SubscriptionServiceRef.UnsubscribeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://github.com/Claude-He/WcfEnsFx/IMyService/GetTime", ReplyAction="https://github.com/Claude-He/WcfEnsFx/IMyService/GetTimeResponse")]
        System.DateTime GetTime();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://github.com/Claude-He/WcfEnsFx/IMyService/GetTime", ReplyAction="https://github.com/Claude-He/WcfEnsFx/IMyService/GetTimeResponse")]
        System.Threading.Tasks.Task<System.DateTime> GetTimeAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMyServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://github.com/Claude-He/WcfEnsFx/IMyService/DemoEvent", ReplyAction="https://github.com/Claude-He/WcfEnsFx/IMyService/DemoEventResponse")]
        void DemoEvent(string strArg);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://github.com/Claude-He/WcfEnsFx/IMyService/DemoEventWithInt", ReplyAction="https://github.com/Claude-He/WcfEnsFx/IMyService/DemoEventWithIntResponse")]
        void DemoEventWithInt(string strArg, int intArg);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Subscribe", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SubscribeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string subscriberName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string eventName;
        
        public SubscribeRequest() {
        }
        
        public SubscribeRequest(string subscriberName, string eventName) {
            this.subscriberName = subscriberName;
            this.eventName = eventName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SubscribeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SubscribeResponse {
        
        public SubscribeResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Unsubscribe", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UnsubscribeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string eventName;
        
        public UnsubscribeRequest() {
        }
        
        public UnsubscribeRequest(string eventName) {
            this.eventName = eventName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UnsubscribeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UnsubscribeResponse {
        
        public UnsubscribeResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMyServiceChannel : MyForms.SubscriptionServiceRef.IMyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyServiceClient : System.ServiceModel.DuplexClientBase<MyForms.SubscriptionServiceRef.IMyService>, MyForms.SubscriptionServiceRef.IMyService {
        
        public MyServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public MyServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public MyServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public MyServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public MyServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyForms.SubscriptionServiceRef.SubscribeResponse MyForms.SubscriptionServiceRef.IMyService.Subscribe(MyForms.SubscriptionServiceRef.SubscribeRequest request) {
            return base.Channel.Subscribe(request);
        }
        
        public void Subscribe(string subscriberName, string eventName) {
            MyForms.SubscriptionServiceRef.SubscribeRequest inValue = new MyForms.SubscriptionServiceRef.SubscribeRequest();
            inValue.subscriberName = subscriberName;
            inValue.eventName = eventName;
            MyForms.SubscriptionServiceRef.SubscribeResponse retVal = ((MyForms.SubscriptionServiceRef.IMyService)(this)).Subscribe(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyForms.SubscriptionServiceRef.SubscribeResponse> MyForms.SubscriptionServiceRef.IMyService.SubscribeAsync(MyForms.SubscriptionServiceRef.SubscribeRequest request) {
            return base.Channel.SubscribeAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyForms.SubscriptionServiceRef.SubscribeResponse> SubscribeAsync(string subscriberName, string eventName) {
            MyForms.SubscriptionServiceRef.SubscribeRequest inValue = new MyForms.SubscriptionServiceRef.SubscribeRequest();
            inValue.subscriberName = subscriberName;
            inValue.eventName = eventName;
            return ((MyForms.SubscriptionServiceRef.IMyService)(this)).SubscribeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyForms.SubscriptionServiceRef.UnsubscribeResponse MyForms.SubscriptionServiceRef.IMyService.Unsubscribe(MyForms.SubscriptionServiceRef.UnsubscribeRequest request) {
            return base.Channel.Unsubscribe(request);
        }
        
        public void Unsubscribe(string eventName) {
            MyForms.SubscriptionServiceRef.UnsubscribeRequest inValue = new MyForms.SubscriptionServiceRef.UnsubscribeRequest();
            inValue.eventName = eventName;
            MyForms.SubscriptionServiceRef.UnsubscribeResponse retVal = ((MyForms.SubscriptionServiceRef.IMyService)(this)).Unsubscribe(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyForms.SubscriptionServiceRef.UnsubscribeResponse> MyForms.SubscriptionServiceRef.IMyService.UnsubscribeAsync(MyForms.SubscriptionServiceRef.UnsubscribeRequest request) {
            return base.Channel.UnsubscribeAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyForms.SubscriptionServiceRef.UnsubscribeResponse> UnsubscribeAsync(string eventName) {
            MyForms.SubscriptionServiceRef.UnsubscribeRequest inValue = new MyForms.SubscriptionServiceRef.UnsubscribeRequest();
            inValue.eventName = eventName;
            return ((MyForms.SubscriptionServiceRef.IMyService)(this)).UnsubscribeAsync(inValue);
        }
        
        public System.DateTime GetTime() {
            return base.Channel.GetTime();
        }
        
        public System.Threading.Tasks.Task<System.DateTime> GetTimeAsync() {
            return base.Channel.GetTimeAsync();
        }
    }
}
